from __future__ import annotations
import click
from pathlib import Path
from core.source_manager import load_sources
from formatters.bibliography import (
    format_article, format_article_4_plus,
    format_book_1_to_3, format_book_4_plus,
    format_internet, format_legislation, format_court,
)

_TESTS_DIR = Path(__file__).parent.parent / "tests"
_OUTPUT_FILE = _TESTS_DIR / "test_generated_bibliography.py"

# Fixed anonymized placeholder data per subtype
_PH_ARTICLE = dict(
    surname="Lastname", initial="A",
    article_title="Sample Article Title",
    journal="Sample Journal",
    issue="Nr. 1", year=2024, pages="1.–10. lpp.",
)
_PH_ARTICLE_4 = dict(
    article_title="Sample Article Title",
    surname="Lastname", initial="A",
    journal="Sample Journal",
    issue="Nr. 1", year=2024, pages="1.–10. lpp.",
)
_PH_BOOK = dict(
    surname="Lastname", initial="A",
    title="Sample Book Title",
    city="Sample City", publisher="Sample Publisher",
    year=2020, pages=300,
)
_PH_BOOK_4 = dict(
    title="Sample Book Title",
    initial="A", surname="Lastname",
    city="Sample City", publisher="Sample Publisher",
    year=2020, pages=300,
)
_PH_LEGISLATION = dict(
    title="Sample Legislation Title",
    adopted_date="01.01.2020.",
    publication="Sample Publication",
    pub_ref="Nr. 1",
    pub_date="01.01.2020.",
)
_PH_INTERNET = dict(
    surname="Lastname", initial="A",
    title="Sample Internet Source",
    url="https://example.com/",
    accessed="01.01.2026.",
)
_PH_COURT = dict(
    case_title="Sample v. Party",
    date="01.01.2024.",
    court="Sample Court Department",
    case_no="SPC-001/2024",
    url="https://example.com/case",
    accessed="01.01.2026.",
)


def _indent(text: str, spaces: int = 8) -> str:
    pad = " " * spaces
    return "\n".join(pad + line if line.strip() else "" for line in text.splitlines())


def _kwargs_repr(d: dict) -> str:
    lines = [f"{k}={v!r}," for k, v in d.items()]
    return "\n".join(lines)


def _build_test(fn_name: str, format_fn_name: str, kwargs: dict, expected: str) -> str:
    kw = _indent(_kwargs_repr(kwargs))
    return (
        f"def {fn_name}():\n"
        f"    result = {format_fn_name}(\n"
        f"{kw}\n"
        f"    )\n"
        f"    assert result == {expected!r}\n"
    )


def _generate_tests_for_subtypes(subtypes: set[str]) -> tuple[list[str], list[str]]:
    """Return (imports_needed, test_function_blocks)."""
    imports: set[str] = set()
    blocks: list[str] = []

    if "article" in subtypes:
        imports.update(["format_article", "format_article_4_plus"])
        blocks.append(_build_test(
            "test_format_article_1_to_3_authors", "format_article",
            _PH_ARTICLE, format_article(**_PH_ARTICLE),
        ))
        blocks.append(_build_test(
            "test_format_article_4_plus_authors", "format_article_4_plus",
            _PH_ARTICLE_4, format_article_4_plus(**_PH_ARTICLE_4),
        ))

    if subtypes & {"book", "monograph"}:
        imports.update(["format_book_1_to_3", "format_book_4_plus"])
        blocks.append(_build_test(
            "test_format_book_1_to_3_authors", "format_book_1_to_3",
            _PH_BOOK, format_book_1_to_3(**_PH_BOOK),
        ))
        blocks.append(_build_test(
            "test_format_book_4_plus_authors", "format_book_4_plus",
            _PH_BOOK_4, format_book_4_plus(**_PH_BOOK_4),
        ))

    if "legislation" in subtypes:
        imports.add("format_legislation")
        blocks.append(_build_test(
            "test_format_legislation", "format_legislation",
            _PH_LEGISLATION, format_legislation(**_PH_LEGISLATION),
        ))

    if "internet" in subtypes:
        imports.add("format_internet")
        blocks.append(_build_test(
            "test_format_internet", "format_internet",
            _PH_INTERNET, format_internet(**_PH_INTERNET),
        ))

    if "court" in subtypes:
        imports.add("format_court")
        blocks.append(_build_test(
            "test_format_court", "format_court",
            _PH_COURT, format_court(**_PH_COURT),
        ))

    return sorted(imports), blocks


def _render_file(imports: list[str], blocks: list[str]) -> str:
    import_line = "from formatters.bibliography import (\n"
    import_line += "".join(f"    {name},\n" for name in imports)
    import_line += ")"
    header = (
        "# Auto-generated by `python3 cli.py generate-tests` — do not edit manually.\n"
        "# Re-run after adding new sources to regenerate.\n"
    )
    return header + "\n" + import_line + "\n\n\n" + "\n\n".join(blocks) + "\n"


@click.command(name="generate-tests")
def generate_tests() -> None:
    """Generate bibliography formatter tests based on active paper's source types."""
    sources = load_sources()
    if not sources:
        click.echo("No sources found in active paper — nothing to generate.", err=True)
        return

    subtypes = {s.get("source_subtype", "") for s in sources if s.get("source_subtype")}
    if not subtypes:
        click.echo("No source_subtype fields found in sources — nothing to generate.", err=True)
        return

    imports, blocks = _generate_tests_for_subtypes(subtypes)
    content = _render_file(imports, blocks)
    _OUTPUT_FILE.write_text(content, encoding="utf-8")

    click.echo(f"Detected subtypes: {', '.join(sorted(subtypes))}")
    click.echo(f"Generated {len(blocks)} test(s) → {_OUTPUT_FILE}")
